#
# Copyright (C) 2020 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
build:
  quality:
    filter:
      owner: graknlabs
      branch: master
    build-analysis:
      machine: graknlabs-ubuntu-20.04
      script: |
        SONARCLOUD_CODE_ANALYSIS_CREDENTIAL=$SONARCLOUD_CREDENTIAL \
          bazel run @graknlabs_dependencies//tool/sonarcloud:code-analysis -- \
          --project-key=graknlabs_common \
          --branch=$GRABL_BRANCH --commit-id=$GRABL_COMMIT
    dependency-analysis:
      machine: graknlabs-ubuntu-20.04
      script: |
        bazel run @graknlabs_dependencies//grabl/analysis:dependency-analysis
  correctness:
    build:
      machine: graknlabs-ubuntu-20.04
      script: |
        bazel build //... --test_output=errors
        bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
        bazel test $(bazel query 'kind(checkstyle_test, //...)')
    build-dependency:
      machine: graknlabs-ubuntu-20.04
      script: |
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
    deploy-maven-snapshot:
      filter:
        owner: graknlabs
        branch: master
      machine: graknlabs-ubuntu-20.04
      dependencies: [build]
      script: |
        export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //:deploy-maven -- snapshot
    deploy-apt-snapshot:
      filter:
        owner: graknlabs
        branch: master
      machine: graknlabs-ubuntu-20.04
      dependencies: [build]
      script: |
        export DEPLOY_APT_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_APT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //binary:deploy-apt -- snapshot
    deploy-rpm-snapshot:
      filter:
        owner: graknlabs
        branch: master
      machine: graknlabs-ubuntu-20.04
      dependencies: [build]
      script: |
        sudo apt-get update && sudo apt-get install rpm
        export DEPLOY_RPM_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_RPM_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //binary:deploy-rpm -- snapshot

release:
  filter:
    owner: graknlabs
    branch: master
  deployment:
    deploy-github:
      machine: graknlabs-ubuntu-20.04
      script: |
        pip install certifi
        export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @graknlabs_dependencies//tool/release:create-notes -- common $(cat VERSION) ./RELEASE_TEMPLATE.md
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
    deploy-maven-release:
      machine: graknlabs-ubuntu-20.04
      dependencies: [deploy-github]
      script: |
        export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(cat VERSION) //:deploy-maven -- release
    deploy-apt-release:
      machine: graknlabs-ubuntu-20.04
      dependencies: [deploy-github]
      script: |
        cat VERSION
        export DEPLOY_APT_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_APT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(cat VERSION) //binary:deploy-apt -- release
    deploy-rpm-release:
      machine: graknlabs-ubuntu-20.04
      dependencies: [deploy-github]
      script: |
        sudo apt-get update && sudo apt-get install rpm
        sed -i -e 's/-/_/g' VERSION 
        export DEPLOY_RPM_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_RPM_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(cat VERSION) //binary:deploy-rpm -- release
